id = "nsis"
name = "NSIS"
description = "NSIS language support for Zed"
version = "0.2.0"
schema_version = 1
authors = ["Jan T. Sott"]
repository = "https://github.com/idleberg/zed-nsis-extension"
languages = ["languages/nsis"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.nsis]
repository = "https://github.com/idleberg/tree-sitter-nsis"
rev = "e8e06f2e07b579b4110207eb251e653acb69e6bc"

[language_servers.nsis-lsp]
name = "NSIS LSP"
languages = ["NSIS"]
