id = "nsis"
name = "NSIS"
description = "NSIS language support for Zed"
version = "0.2.0"
schema_version = 1
authors = ["Jan T. Sott"]
repository = "https://github.com/idleberg/zed-nsis-extension"
languages = ["languages/nsis"]

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.nsis]
repository = "https://github.com/idleberg/tree-sitter-nsis"
rev = "4b6c1260fcf7d2e1ce64164085d2bdb4e3e65ed8"

[language_servers.nsis-lsp]
name = "NSIS LSP"
languages = ["NSIS"]
